name: Gradr Code Review

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Prepare To Install
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Deps
      run: |
        yarn install
        yarn add axios jest
    - name: Run Audits
      run: yarn test
    - name: Report Audit Stats
      uses: ./.github/actions/out
      if: success()
