name: Gradr Code Review

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Code Audit
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Prepare To Install & Build 
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Deps & Build 
      run: |
        npm install
        npm install -g jest-cli
        npm run build --if-present
    - name: Prepare Audits
      uses: actions/checkout@v2
      with: 
        repository: chalu/devc-frontend-audits
        path: audits
    - name: Check Code
      run: jest
      env:
        CI: true
