name: Gradr

on:
  pull_request:
    branches:
    - master

jobs:
  ft-1:
    name: audit feature 1
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Cache Deps
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm 
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Prepare To Install
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Deps
      run: |
        yarn install
        yarn add jest

    - name: Run Audits
      run: yarn ft-1

    - name: Report Audit Stats
      uses: ./.github/actions/ft-1
      if: success()
  
  ft-2:
    needs: ft-1
    name: audit feature 2
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Prepare To Install
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Deps
      run: |
        yarn install
        yarn add jest
        
    - name: Run Audits
      run: yarn ft-2

    - name: Report Audit Stats
      uses: ./.github/actions/ft-2
      if: success()

  ft-3:
    needs: ft-2
    name: audit feature 3
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Prepare To Install
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Deps
      run: |
        yarn install
        yarn add jest
        
    - name: Run Audits
      run: yarn ft-3

    - name: Report Audit Stats
      uses: ./.github/actions/ft-3
      if: success()
